name: Publish
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build_tarballs:
    name: Build tarballs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - name: Build tarballs
        run: |
          nix build -L .#hydraJobs.tarball
          install -D ./result/tarballs/*.tar.bz2 ./dist/patchelf-$(cat version).tar.bz2
          install -D ./result/tarballs/*.tar.gz ./dist/patchelf-$(cat version).tar.gz
      - uses: actions/upload-artifact@v4
        with:
          name: patchelf-tarball
          path: dist/*

  build_musl:
    name: Build static musl binaries
    needs: [build_tarballs]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: ["arm64", "amd64"]
    steps:
      - name: Set up QEMU
        if: matrix.platform != 'amd64'
        uses: docker/setup-qemu-action@v3

      - name: Set docker arch
        run: |
          platform=${{ matrix.platform }}
          if [[ $platform == arm64v8 ]]; then
            platform=arm64
          elif [[ $platform == arm32v7 ]]; then
            platform=arm
          fi
          echo "DOCKER_PLATFORM=$platform" >> $GITHUB_ENV

      - uses: actions/download-artifact@v4
        with:
          name: patchelf-tarball
          path: dist
      - name: Build binaries
        env:
          CXXFLAGS: "-D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wformat -Werror=format-security -O2 -static"
        run: |
          cat <<EOF > build.sh
          set -e
          set -x
          apk add build-base
          tar -xf dist/*.tar.bz2
          rm -f dist/*
          cd patchelf-*
          ./configure --prefix /patchelf
          make check || (cat tests/test-suite.log; exit 1)
          make install-strip
          cd -
          tar -czf ./dist/patchelf-\$(cat patchelf-*/version)-\$(uname -m).tar.gz -C /patchelf .
          EOF

          if [ "${{ matrix.platform }}" == "i386" ]; then
              ENTRYPOINT=linux32
          else
              ENTRYPOINT=
          fi
          docker run --platform "$DOCKER_PLATFORM" -e CXXFLAGS -v $(pwd):/gha alpine:edge ${ENTRYPOINT} sh -ec "cd /gha && sh ./build.sh"

      - uses: actions/upload-artifact@v4
        with:
          name: patchelf-${{ matrix.platform }}
          path: dist/*

          overwrite: true
          file_glob: true

  publish:
    name: Publish tarballs & binaries
    needs: [build_musl]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: patchelf-*
          merge-multiple: true
          path: dist

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
